/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo5;

public class App {


    public static void main(String[] args) {
        linkedList<String> newlist = new linkedList();
        newlist.addFirst("Roaa");
        newlist.addFirst("Ahmad");
        newlist.addLast("Manar");
        newlist.printAllItems();
    }
}
