/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package class08.demo;

import com.google.gson.Gson;

public class App {


    public static void main(String[] args) {
        Contact roaa = new Contact("roaa","Abu Aligah",26);
        Gson gson = new Gson();
        String roaaJSON = gson.toJson(roaa);
        System.out.println(roaaJSON);

        Contact roaaObj = gson.fromJson(roaaJSON, Contact.class);
        System.out.println(roaaObj);

        String ahmadJson = "{\"firstName\":\"ahmad\",\"lastName\":\"ali\",\"age\":20}";
        Contact ahmadObj = gson.fromJson(ahmadJson, Contact.class);
        System.out.println(ahmadObj);

        String johnJson = "{\"firstName\":\"John\",\"lastName\":\"Smith\",\"age\":25," +
                "  \"address\": {" +
                "    \"streetAddress\": \"21 2nd Street\"," +
                "    \"city\": \"New York\"," +
                "    \"state\": \"NY\"," +
                "    \"postalCode\": 10021" +
                "  }}";

        Contact johnObj = gson.fromJson(johnJson,Contact.class);
        System.out.println(johnObj);

        Address address = new Address("street1","Amman","Amman",11022);
        String addressStr = gson.toJson(address);
        System.out.println(addressStr);

        Address addressObj = gson.fromJson(addressStr,Address.class);
        System.out.println(addressObj);
    }
}
