/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {

    public static void main(String[] args) {
        Graph graph = new Graph();

        graph.addVertex("A");
        graph.addVertex("B");
        graph.addVertex("C");

        graph.addEdges("A","B");
        graph.addEdges("B","C");
        graph.addEdges("A","C");

        System.out.println(graph.printGraph());

//        graph.removeVertex("B");
//        graph.removeEdge("A","B");



        System.out.println(graph.bfs(graph,"A"));

    }
}
